services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mon-app:latest          # ← correspond à IMAGE_NAME dans le Jenkinsfile
    container_name: mon-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
    volumes:
      - ./reports:/app/reports     # ← persiste les rapports Trivy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
